### ISSUE TITLE
3D reconstruction

### ISSUE THREAD

**Issue by tkzeng** [kekeblom/StrayVisualizer#7]
I have gotten quite poor results using the full Open3D reconstruction process, while using StrayVisualizer's --integrate works much better. The main difference is I am only using 1/10th of the frames for Open3D, since using all frames takes forever. 

Have you been able to achieve good results with Open3D? I'm not sure if there are some parameters I need to adjust.

**Comment by kekeblom** [comment]
Is the reconstruction completely destroyed or just bad in certain scenarios? Did you use only the high confidence measurements?

It is not perfect, but Open3D does a reasonably good job at scene level reconstruction. Smaller details are not that well reconstructed. It uses depth for odometry, so it kind of depends on the scene how well that works. Scenes where there are planes in several directions (e.g. indoor walls) tend to work quite well. 

Hard to say if your bad results are due to drift in the odometry, noise in the depth, bad parameters with respect to scale or something else.
